version: '3.9'

services:
  base-ecommerce-redis:
    container_name: base-ecommerce-redis
    image: redis:alpine
    restart: always
    env_file: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '$REDIS_PORT:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - base_ecommerce_redis_data:/data

  base-ecommerce-postgres:
    container_name: base-ecommerce-postgres
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '$POSTGRES_PORT:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - base_ecommerce_postgres_data:/var/lib/postgresql

volumes:
  base_ecommerce_postgres_data:
  base_ecommerce_redis_data:
